AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Automating document vectorization using OpenSearch and Bedrock
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  AmazonOpenSearchCollectionName:
    Type: String
    Description: "The collection name to create for storing vector embeddings"
    ConstraintDescription: "Must be a valid name for Amazon OpenSearch Service Collection."
    Default: "examplecollection"
  AmazonOpenSearchIndexName:
    Type: String
    Description: "The index name to store vector embeddings"
    ConstraintDescription: "Must be a valid Amazon OpenSearch Service Vector Index."
    Default: "example-index"
  BedrockModelRegion:
    Type: String
    Description: Select the Bedrock service region.
    AllowedValues:
      - us-east-1
      - us-west-2
      - eu-central-1
      - ap-northeast-1
      - ap-southeast-1
    Default: us-west-2
  UserName:
    Type: String
    Default: "eya"
    Description: "IAM username to grant access to"
Resources:
  LambdaInvokeIndexCreation:
    Type: Custom::InvokeIndexCreation
    Properties:
      ServiceToken: !GetAtt IndexCreationLambdaFunction.Arn
      AOSSIndexName: !Ref AmazonOpenSearchIndexName
      AOSSHost:  !Sub '${ExampleCollection.CollectionEndpoint}'

  IndexCreationLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaAOSSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - aoss:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - aoss:DashboardsAccessAll
                Resource: !Sub 'arn:aws:aoss:${AWS::Region}:${AWS::AccountId}:dashboards/default'

  IndexCreationLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:  src/functions/
      Handler: index_creation.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 120
      Role: !GetAtt IndexCreationLambdaExecutionRole.Arn
      Layers:
        - !Ref DependenciesLibrary

  UnifiedBedrockExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - s3.amazonaws.com
                - bedrock.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: UnifiedAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Describe*
                  - s3-object-lambda:Get*
                  - s3-object-lambda:List*
                Resource:
                  - !Sub "arn:aws:s3:::${SourceBucket}/*"
                  - !Sub "arn:aws:s3:::${SourceBucket}"
              - Effect: Allow
                Action:
                  - aoss:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource: !Sub arn:aws:aoss:${AWS::Region}:${AWS::AccountId}:collection/*
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:ListFoundationModels
                  - bedrock:ListCustomModels
                  - bedrock:RetrieveAndGenerate
                  - bedrock:StartIngestionJob
                Resource:
                  - '*'
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*



  DependenciesLibrary:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: document-ingestion-libs
      Description: Dependencies for the document ingestion function
      ContentUri: src/dependencies
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  SourceDocumentsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SourceBucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Effect: Deny
            Principal: '*'
            Resource:
              - !Sub arn:aws:s3:::${SourceBucket}/*
              - !Sub arn:aws:s3:::${SourceBucket}
            Condition:
              Bool:
                aws:SecureTransport: false

  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "encryption-policy-${AWS::StackName}"
      Type: encryption
      Description: Encryption policy for example collection
      Policy: !Sub '{"Rules":[{"ResourceType":"collection","Resource":["collection/${AmazonOpenSearchCollectionName}"]}],"AWSOwnedKey":true}'

  SecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "network-policy-${AWS::StackName}"
      Type: network
      Description: Network policy for example collections
      Policy: !Sub '[{"Rules":[{"ResourceType":"collection","Resource":["collection/${AmazonOpenSearchCollectionName}"]}, {"ResourceType":"dashboard","Resource":["collection/${AmazonOpenSearchCollectionName}"]}],"AllowFromPublic":true}]'

  ExampleCollection:
    Type: AWS::OpenSearchServerless::Collection
    Properties:
      Name: !Ref AmazonOpenSearchCollectionName
      Description: Example collection for RAG applications
      Type: VECTORSEARCH
    DependsOn:
      - EncryptionPolicy
      - SecurityPolicy
      - AccessPolicy

  AccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub "access-policy-${AWS::StackName}"
      Type: data
      Description: Access policy for the collection
      Policy: !Sub '[{"Description":"Access for Users","Rules":[{"ResourceType":"index","Resource":["index/${AmazonOpenSearchCollectionName}/${AmazonOpenSearchIndexName}"],"Permission":["aoss:*"]}, {"ResourceType":"collection","Resource":["collection/${AmazonOpenSearchCollectionName}"],"Permission":["aoss:*"]}], "Principal":["${UnifiedBedrockExecutionRole.Arn}","${IndexCreationLambdaExecutionRole.Arn}"]}]'



Outputs:
  S3Bucket:
    Value: !GetAtt SourceBucket.Arn
    Export:
      Name: !Sub "${AWS::EnvironmentName}-s3bucket"

  S3BucketName:
    Value: !Ref SourceBucket
    Description: S3 Bucket for object storage
    Export:
      Name: !Sub "${AWS::EnvironmentName}-s3bucketname"




  DashboardURL:
    Value: !GetAtt ExampleCollection.DashboardEndpoint
    Export:
      Name: !Sub "${AWS::EnvironmentName}-dashboardurl"

  DocumentIngestionLambdaExecutionRole:
    Value: !GetAtt UnifiedBedrockExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::EnvironmentName}-documentingestionlambdaexecutionrole"

  CollectionARN:
    Value: !GetAtt ExampleCollection.Arn
    Description: Collection ARN for the created collection
    Export:
      Name: !Sub "${AWS::EnvironmentName}-collectionarn"

  OpenSearchIndexName:
    Description: "Name of the created OpenSearch index"
    Value: !Ref AmazonOpenSearchIndexName
    Export:
      Name: !Sub "${AWS::EnvironmentName}-opensearchindexname"
