#defining cloudformation standard version
AWSTemplateFormatVersion: '2010-09-09'
Description: "EC2 Auto Scaling with ALB FOR EXISITING ec2 instance"
Parameters:
  #step 1 :defining the vpc and subnet of the instances
  VPCId:
    Type: String
    Default: vpc-e282698b
  SubnetId1:
    Type: String
    Default: subnet-ff5b5087
  SubnetId2:
    Type: String
    Default: subnet-66749d0f
  AMIId:
    Type: String
    Description: AMI ID from the AMI creation stage

Resources:
  #step 2: configuring the Launch template for launching the instance
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC2Template
      LaunchTemplateData:
        ImageId: !Ref AMIId
        InstanceType: g4dn.xlarge
        KeyName: virtual_key_ollama_server
        SecurityGroupIds: #firewall configuration
          - sg-0a5aff45d72a354b1
        DisableApiTermination: true

  #step 3 : defining the Autoscaling group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref SubnetId1
        - !Ref SubnetId2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      TargetGroupARNs:
        - !Ref TargetGroup
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300

  # GPU Scaling Policy - Scale Out
  GPUScaleOutPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalLowerBound: 0
          ScalingAdjustment: 1
      MetricAggregationType: Average

  # GPU Scaling Policy - Scale In
  GPUScaleInPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments:
        - MetricIntervalUpperBound: 0
          ScalingAdjustment: -1
      MetricAggregationType: Average

  # CloudWatch Alarm - GPU High
  GPUHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: GPU-Utilization-High
      AlarmDescription: Alarm when GPU exceeds 50%
      MetricName: GPUUtilization
      Namespace: CWAgent
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref GPUScaleOutPolicy

  # CloudWatch Alarm - GPU Low
  GPULowAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: GPU-Utilization-Low
      AlarmDescription: Alarm when GPU below 20%
      MetricName: GPUUtilization
      Namespace: CWAgent
      Statistic: Average
      Period: 300
      EvaluationPeriods: 3
      Threshold: 20
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref GPUScaleInPolicy

    #step 4 : defining the tagetgroup it's routing the trafic from ALB to instances
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: EC2TargetGroup
      Port: 8001
      Protocol: HTTP
      VpcId: !Ref VPCId
      TargetType: instance
      HealthCheckPath: /collection/
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 60
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
    #step5 :  defining a Load Balancer ALB
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: EC2LoadBalancer
      Subnets:
        - !Ref SubnetId1
        - !Ref SubnetId2
      SecurityGroups:
        - sg-0a5aff45d72a354b1
      Type: application
      Scheme: internet-facing #means that the ALB is accessible from the internet
      IpAddressType: ipv4
    #step 6 : defining the ALB listener
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 8001
      Protocol: HTTP

# step 7 : the outputs
Outputs:
  LoadBalancerDNS:
    Description: "DNS name of the Load Balancer"
    Value: !GetAtt LoadBalancer.DNSName


#note to self we don't need policies here because ec2 dosen't need access to any services


