AWSTemplateFormatVersion: '2010-09-09'
Description: Reusable IAM roles for OpenSearch + Bedrock document vectorization

Parameters:

Resources:
  IndexCreationLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IndexCreationLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaAOSSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - aoss:*
                  - aoss:DashboardsAccessAll
                Resource: "*"

  BedrockExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BedrockExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - s3.amazonaws.com
                - bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: UnifiedAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Describe*
                  - s3-object-lambda:Get*
                  - s3-object-lambda:List*
                Resource: "*"
              - Effect: Allow
                Action: aoss:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:ListFoundationModels
                  - bedrock:ListCustomModels
                  - bedrock:RetrieveAndGenerate
                  - bedrock:StartIngestionJob
                Resource: "*"



  EncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "encryption-policy-${AWS::StackName}"
      Type: encryption
      Description: Encryption policy for example collection
      Policy: !Sub '{"Rules":[{"ResourceType":"collection","Resource":["collection/${AmazonOpenSearchCollectionName}"]}],"AWSOwnedKey":true}'

  SecurityPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub "network-policy-${AWS::StackName}"
      Type: network
      Description: Network policy for example collections
      Policy: !Sub '[{"Rules":[{"ResourceType":"collection","Resource":["collection/${AmazonOpenSearchCollectionName}"]}, {"ResourceType":"dashboard","Resource":["collection/${AmazonOpenSearchCollectionName}"]}],"AllowFromPublic":true}]'
  AccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub "access-policy-${AWS::StackName}"
      Type: data
      Description: Access policy for the collection
      Policy: !Sub '[{"Description":"Access for Users","Rules":[{"ResourceType":"index","Resource":["index/${AmazonOpenSearchCollectionName}/${AmazonOpenSearchIndexName}"],"Permission":["aoss:*"]}, {"ResourceType":"collection","Resource":["collection/${AmazonOpenSearchCollectionName}"],"Permission":["aoss:*"]}], "Principal":["${BedrockExecutionRole.Arn}","${IndexCreationLambdaExecutionRole.Arn}"]}]'
Outputs:
  IndexCreationLambdaExecutionRoleArn:
    Value: !GetAtt IndexCreationLambdaExecutionRole.Arn
    Export:
      Name: IndexCreationLambdaExecutionRoleArn

  BedrockExecutionRoleArn:
    Value: !GetAtt BedrockExecutionRole.Arn
    Export:
      Name: BedrockExecutionRoleArn
